Added `travis_retry` to macOS install command line tools.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -156,6 +156,9 @@ jobs:
     os: linux
     name: "Final deploy to DockerHub"
     
+    #before_install:
+    #- set -e # Fail the whole script whenever any command fails
+
 install:
 - |   
   if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
@@ -175,14 +178,7 @@ install:
     mkdir current
     tar -xJf $HOME/Library/Caches/Homebrew/clang+llvm-${LLVM_VERSION}-x86_64-apple-darwin.tar.xz -C current --strip-components 1    
     # Temporary fix for image: xcode11 to use GCC.
-    # Source: https://github.com/Farwaykorse/fwkSudoku/commit/9dff745e37390abcfacd6e4f8da650e7db54444e
-    # backup the date
-    ORG_DATE=`date +%m%d%H%M%Y`
-    sudo date 101918002019
-    date
-    sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -allowUntrusted -target /
-    # set the date to the inital value
-    sudo date ${ORG_DATE}
+    travis_retry $TRAVIS_BUILD_DIR/scripts/travis-install-macos-commandline-tools.sh
   fi
 - |
   if [[ "${UPLOAD}" = "Yes" ]]; then
